spring:
  datasource:
    url: jdbc:mysql://localhost/image_server?useSSL=false&serverTimezone=UTC
    username: image_server
    password: image_server
    driverClassNam: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      
server:
  port: 8080